# Generated by Django 4.2.5 on 2023-09-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_seller',
            new_name='is_educator',
        ),
        migrations.AddField(
            model_name='user',
            name='issue',
            field=models.ManyToManyField(to='core.issues'),
        ),
    ]
