# Generated by Django 3.2.21 on 2023-09-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_user_is_employer_job_enrolledcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.issues'),
        ),
    ]
